AWSTemplateFormatVersion: 2010-09-09 
 
Parameters: 
  ApplicationName: 
    Type: String 
  EnvironmentName:
    Type: String 
  InstanceType:
    Type: String
  KeyPairName:
    Type: String 
  VpcId:
    Type: String 
  SubnetId:
    Type: String 
  ELBSubnetId:
    Type: String 
  MinSize:
    Type: String
  MaxSize:
    Type: String
  Cooldown:
    Type: String
Resources: 
  EBApplication: 
    Type: AWS::ElasticBeanstalk::Application 
    Properties: 
      ApplicationName: !Ref ApplicationName
  EBApplicationVersion: 
    Type: AWS::ElasticBeanstalk::ApplicationVersion 
    Properties: 
      ApplicationName: !Ref 'EBApplication' 
      SourceBundle: 'bin.zip' 
  EBConfigurationTemplate: 
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate 
    Properties: 
      ApplicationName: !Ref 'EBApplication' 
      OptionSettings: 
      - Namespace: aws:elasticbeanstalk:environment 
        OptionName: EnvironmentType 
        Value: LoadBalanced 
      - Namespace: aws:elasticbeanstalk:healthreporting:system 
        OptionName: SystemType 
        Value: enhanced
      # see: https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html
      SolutionStackName: '64bit Amazon Linux 2018.03 v2.15.1 running Go 1.14.1'
  EBEnvironment: 
    Type: AWS::ElasticBeanstalk::Environment 
    Properties: 
      ApplicationName: !Ref 'EBApplication' 
      EnvironmentName: !Ref 'EnvironmentName' 
      TemplateName: !Ref 'EBConfigurationTemplate' 
      VersionLabel: !Ref 'EBApplicationVersion' 
      OptionSettings:
        # see: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-environment.html
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: aws-elasticbeanstalk-ec2-role
      - Namespace: aws:autoscaling:launchconfiguration 
        OptionName: InstanceType 
        Value: !Ref 'InstanceType' 
      - Namespace: aws:autoscaling:launchconfiguration 
        OptionName: EC2KeyName 
        Value: !Ref 'KeyPairName' 
      - Namespace: aws:ec2:vpc 
        OptionName: VPCId 
        Value: !Ref 'VpcId' 
      - Namespace: 'aws:ec2:vpc'
        OptionName: Subnets 
        Value: !Ref 'SubnetId' 
      - Namespace: 'aws:ec2:vpc'
        OptionName: ELBSubnets 
        Value: !Ref 'ELBSubnetId'
        # see: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.managing.vpc.html#environments-cfg-vpc-namespace
      - Namespace: aws:ec2:vpc
        OptionName: 'AssociatePublicIpAddress'
        Value: trueÀù
      - Namespace: aws:ec2:vpc
        OptionName: 'ELBScheme'
        Value: false
      - Namespace: aws:autoscaling:asg 
        OptionName: Availability Zones 
        Value: Any
      - Namespace: aws:autoscaling:asg 
        OptionName: Cooldown
        Value: !Ref 'Cooldown'
      - Namespace: aws:autoscaling:asg 
        OptionName: MaxSize
        Value: !Ref 'MaxSize'
      - Namespace: aws:autoscaling:asg 
        OptionName: MinSize
        Value: !Ref 'MinSize'