version: 0.2

phases:
  install:
    runtime-versions:
       docker: 19
       golang: 1.14
    commands:
       - pip install --upgrade awscli
  pre_build:
    commands:
       - go test
       - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-w -s' -o bin/application main.go
  build:
    commands:
      # - mkdir deploy
      - cp $USE_TEMPLATE_FILE_PATH .
      # - cp -r ./bin ./deploy
      # - cd deploy
      - aws cloudformation package
        --template-file template.yaml
        --s3-bucket $S3_BUCKET
        --output-template-file template-export.yaml
artifacts:
  files:
    - template-export.yaml