version: 0.2

phases:
  install:
    runtime-versions:
       docker: 19
       golang: 1.14
    commands:
       - pip install --upgrade awscli
  pre_build:
    commands:
      - go test
  build:
    commands:
      # - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-s' -o application application.go
      - go build -o bin/application application.go
  post_build:
    commands:
      - cp $USE_TEMPLATE_FILE_PATH .
      - aws cloudformation package
        --template-file template.yaml
        --s3-bucket $S3_BUCKET
        --output-template-file template-export.yaml
artifacts:
  files:
    - template-export.yaml